# Shared helpers for the probe emitters. Sourced by probe.sh.

# Identify the cluster. Ranked by robustness across execution contexts:
# /etc/xthostname is a root-owned file and is present regardless of shell type,
# whereas $CLUSTER_NAME is set by /etc/profile.d/cscs.sh and is empty in a
# non-login shell (as used by `ssh host 'command'` and by FirecREST).
probe_cluster() {
    if [[ -r /etc/xthostname ]]; then
        sed 's/^alps-//' /etc/xthostname
    elif [[ -n "${CLUSTER_NAME:-}" ]]; then
        echo "$CLUSTER_NAME"
    elif [[ -r /etc/uenv/config.toml ]]; then
        sed -n "s/^system_name *= *'\\(.*\\)'/\\1/p" /etc/uenv/config.toml
    else
        echo "probe_cluster: cannot determine cluster" >&2
        return 1
    fi
}

# Hash of the emitters, so a change to the generator is visible in the artifacts
# and signals that they should be regenerated. Deterministic; no git required.
probe_emitters_sha() {
    cat "${PROBE_ROOT}/probe.sh" "${PROBE_ROOT}"/lib/*.sh | sha256sum | cut -c1-8
}

# Remove user- and project-specific identifiers. Generated artifacts are
# committed to a public repository, so redaction happens here rather than in
# review: a reviewer cannot be relied on to spot a leak in a large diff.
probe_redact() {
    local group
    group="$(id -gn)"
    sed -e "s|/${USER}\\b|/\$USER|g" \
        -e "s|\\b${USER}\\b|\$USER|g" \
        -e "s|/${group}\\b|/\$GROUP|g"
}

# Fragment header. Carries no date and no hostname, so that re-running the
# emitters produces an empty diff when the system configuration has not changed.
probe_header() {
    local source_cmd="$1"
    cat <<EOF
<!-- Generated by probes/probe.sh from: ${source_cmd}
     Do not edit. Regenerate by running probes/probe.sh on ${PROBE_CLUSTER}.
     cluster: ${PROBE_CLUSTER}  emitters: ${PROBE_EMITTERS_SHA} -->

EOF
}
