name: First interaction message

on:
  pull_request_target:
    types: [opened]
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v3
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        pr_message: |
          Thank you for your contribution to eth-cscs/cscs-docs.

          If you have not done so already, please take some time to get familiar with the [contributing guidelines](https://docs.cscs.ch/contributing/).
          Following the guidelines helps us keep the documentation consistent and as useful as possible for users.
        issue_message: ''
